/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import common.Item;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dulan
 */
public class mainwindow extends javax.swing.JFrame {

    /**
     * Creates new form mainwindow
     */
    int timeRun = 0;
    static Socket socket;

    public mainwindow() {
        initComponents();
        getClock();
        connectSocket();
        jButton1.setEnabled(false);
//        getAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        item1ID = new javax.swing.JLabel();
        item1desc = new javax.swing.JLabel();
        item1AvailableQty = new javax.swing.JLabel();
        item1Price = new javax.swing.JLabel();
        item1Qty = new javax.swing.JTextField();
        item1AddToCart = new javax.swing.JButton();
        item1Rate = new javax.swing.JLabel();
        item2desc = new javax.swing.JLabel();
        item2Rate = new javax.swing.JLabel();
        item2ID = new javax.swing.JLabel();
        item2Price = new javax.swing.JLabel();
        item2AvailableQty = new javax.swing.JLabel();
        item2Qty = new javax.swing.JTextField();
        item2AddToCart = new javax.swing.JButton();
        item4desc = new javax.swing.JLabel();
        item4ID = new javax.swing.JLabel();
        item4Qty = new javax.swing.JTextField();
        item4AddToCart = new javax.swing.JButton();
        item4Rate = new javax.swing.JLabel();
        item4Price = new javax.swing.JLabel();
        item4AvailableQty = new javax.swing.JLabel();
        item3desc = new javax.swing.JLabel();
        item3Rate = new javax.swing.JLabel();
        item3ID = new javax.swing.JLabel();
        item3Price = new javax.swing.JLabel();
        item3AvailableQty = new javax.swing.JLabel();
        item3Qty = new javax.swing.JTextField();
        item3AddToCart = new javax.swing.JButton();
        item5Rate = new javax.swing.JLabel();
        item5Price = new javax.swing.JLabel();
        item5AddToCart = new javax.swing.JButton();
        item6ID = new javax.swing.JLabel();
        item6AvailableQty = new javax.swing.JLabel();
        item5desc = new javax.swing.JLabel();
        item5Qty = new javax.swing.JTextField();
        item6Qty = new javax.swing.JTextField();
        item6desc = new javax.swing.JLabel();
        item5AvailableQty = new javax.swing.JLabel();
        item5ID = new javax.swing.JLabel();
        item6Rate = new javax.swing.JLabel();
        item6AddToCart = new javax.swing.JButton();
        item6Price = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ZeeLot Company");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Oldstyle", 1, 30)); // NOI18N
        jLabel1.setText("Welcome to ZeeLot Company");

        timeLabel.setFont(new java.awt.Font("Time", 1, 24)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Description");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Price");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Available Qty");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Qty");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("<<");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("pg");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText(">>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        item1ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item1ID.setText("jLabel9");
        jPanel5.add(item1ID);
        item1ID.setBounds(120, 40, 80, 20);

        item1desc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item1desc.setText("jLabel9");
        jPanel5.add(item1desc);
        item1desc.setBounds(10, 10, 190, 20);

        item1AvailableQty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item1AvailableQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        item1AvailableQty.setText("jLabel11");
        jPanel5.add(item1AvailableQty);
        item1AvailableQty.setBounds(360, 20, 80, 20);

        item1Price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item1Price.setText("jLabel11");
        jPanel5.add(item1Price);
        item1Price.setBounds(230, 20, 100, 20);

        item1Qty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        item1Qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item1QtyActionPerformed(evt);
            }
        });
        jPanel5.add(item1Qty);
        item1Qty.setBounds(480, 20, 60, 23);

        item1AddToCart.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        item1AddToCart.setText("Add To Cart");
        item1AddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item1AddToCartActionPerformed(evt);
            }
        });
        jPanel5.add(item1AddToCart);
        item1AddToCart.setBounds(570, 20, 150, 23);

        item1Rate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item1Rate.setText("jLabel9");
        jPanel5.add(item1Rate);
        item1Rate.setBounds(10, 40, 80, 20);

        item2desc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item2desc.setText("jLabel9");
        jPanel5.add(item2desc);
        item2desc.setBounds(10, 80, 190, 20);

        item2Rate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item2Rate.setText("jLabel9");
        jPanel5.add(item2Rate);
        item2Rate.setBounds(10, 110, 80, 20);

        item2ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item2ID.setText("jLabel9");
        jPanel5.add(item2ID);
        item2ID.setBounds(120, 110, 80, 20);

        item2Price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item2Price.setText("jLabel11");
        jPanel5.add(item2Price);
        item2Price.setBounds(230, 90, 100, 20);

        item2AvailableQty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item2AvailableQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        item2AvailableQty.setText("jLabel11");
        jPanel5.add(item2AvailableQty);
        item2AvailableQty.setBounds(360, 90, 80, 20);

        item2Qty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        item2Qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item2QtyActionPerformed(evt);
            }
        });
        jPanel5.add(item2Qty);
        item2Qty.setBounds(480, 90, 60, 23);

        item2AddToCart.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        item2AddToCart.setText("Add To Cart");
        item2AddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item2AddToCartActionPerformed(evt);
            }
        });
        jPanel5.add(item2AddToCart);
        item2AddToCart.setBounds(570, 90, 150, 23);

        item4desc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item4desc.setText("jLabel9");
        jPanel5.add(item4desc);
        item4desc.setBounds(10, 220, 190, 20);

        item4ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item4ID.setText("jLabel9");
        jPanel5.add(item4ID);
        item4ID.setBounds(120, 250, 80, 20);

        item4Qty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        item4Qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item4QtyActionPerformed(evt);
            }
        });
        jPanel5.add(item4Qty);
        item4Qty.setBounds(480, 230, 60, 23);

        item4AddToCart.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        item4AddToCart.setText("Add To Cart");
        item4AddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item4AddToCartActionPerformed(evt);
            }
        });
        jPanel5.add(item4AddToCart);
        item4AddToCart.setBounds(570, 230, 150, 23);

        item4Rate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item4Rate.setText("jLabel9");
        jPanel5.add(item4Rate);
        item4Rate.setBounds(10, 250, 80, 20);

        item4Price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item4Price.setText("jLabel11");
        jPanel5.add(item4Price);
        item4Price.setBounds(230, 230, 100, 20);

        item4AvailableQty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item4AvailableQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        item4AvailableQty.setText("jLabel11");
        jPanel5.add(item4AvailableQty);
        item4AvailableQty.setBounds(360, 230, 80, 20);

        item3desc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item3desc.setText("jLabel9");
        jPanel5.add(item3desc);
        item3desc.setBounds(10, 150, 190, 20);

        item3Rate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item3Rate.setText("jLabel9");
        jPanel5.add(item3Rate);
        item3Rate.setBounds(10, 180, 80, 20);

        item3ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item3ID.setText("jLabel9");
        jPanel5.add(item3ID);
        item3ID.setBounds(120, 180, 80, 20);

        item3Price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item3Price.setText("jLabel11");
        jPanel5.add(item3Price);
        item3Price.setBounds(230, 160, 100, 20);

        item3AvailableQty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item3AvailableQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        item3AvailableQty.setText("jLabel11");
        jPanel5.add(item3AvailableQty);
        item3AvailableQty.setBounds(360, 160, 80, 20);

        item3Qty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        item3Qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item3QtyActionPerformed(evt);
            }
        });
        jPanel5.add(item3Qty);
        item3Qty.setBounds(480, 160, 60, 23);

        item3AddToCart.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        item3AddToCart.setText("Add To Cart");
        item3AddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item3AddToCartActionPerformed(evt);
            }
        });
        jPanel5.add(item3AddToCart);
        item3AddToCart.setBounds(570, 160, 150, 23);

        item5Rate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item5Rate.setText("jLabel9");
        jPanel5.add(item5Rate);
        item5Rate.setBounds(10, 320, 80, 20);

        item5Price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item5Price.setText("jLabel11");
        jPanel5.add(item5Price);
        item5Price.setBounds(230, 300, 100, 20);

        item5AddToCart.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        item5AddToCart.setText("Add To Cart");
        item5AddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item5AddToCartActionPerformed(evt);
            }
        });
        jPanel5.add(item5AddToCart);
        item5AddToCart.setBounds(570, 300, 150, 23);

        item6ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item6ID.setText("jLabel9");
        jPanel5.add(item6ID);
        item6ID.setBounds(120, 390, 80, 20);

        item6AvailableQty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item6AvailableQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        item6AvailableQty.setText("jLabel11");
        jPanel5.add(item6AvailableQty);
        item6AvailableQty.setBounds(360, 370, 80, 20);

        item5desc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item5desc.setText("jLabel9");
        jPanel5.add(item5desc);
        item5desc.setBounds(10, 290, 190, 20);

        item5Qty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        item5Qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item5QtyActionPerformed(evt);
            }
        });
        jPanel5.add(item5Qty);
        item5Qty.setBounds(480, 300, 60, 23);

        item6Qty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        item6Qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item6QtyActionPerformed(evt);
            }
        });
        jPanel5.add(item6Qty);
        item6Qty.setBounds(480, 370, 60, 23);

        item6desc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item6desc.setText("jLabel9");
        jPanel5.add(item6desc);
        item6desc.setBounds(10, 360, 190, 20);

        item5AvailableQty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item5AvailableQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        item5AvailableQty.setText("jLabel11");
        jPanel5.add(item5AvailableQty);
        item5AvailableQty.setBounds(360, 300, 80, 20);

        item5ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item5ID.setText("jLabel9");
        jPanel5.add(item5ID);
        item5ID.setBounds(120, 320, 80, 20);

        item6Rate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item6Rate.setText("jLabel9");
        jPanel5.add(item6Rate);
        item6Rate.setBounds(10, 390, 80, 20);

        item6AddToCart.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        item6AddToCart.setText("Add To Cart");
        item6AddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item6AddToCartActionPerformed(evt);
            }
        });
        jPanel5.add(item6AddToCart);
        item6AddToCart.setBounds(570, 370, 150, 23);

        item6Price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item6Price.setText("jLabel11");
        jPanel5.add(item6Price);
        item6Price.setBounds(230, 370, 100, 20);

        jScrollPane1.setViewportView(jPanel5);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Order Summery");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Item ID", "Qty", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("0.00");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Total Amount");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Payment");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Balance");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("0.00");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Confirm Order");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void item1QtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item1QtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item1QtyActionPerformed

    private void item2QtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item2QtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item2QtyActionPerformed

    private void item4QtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item4QtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item4QtyActionPerformed

    private void item3QtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item3QtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item3QtyActionPerformed

    private void item5QtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item5QtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item5QtyActionPerformed

    private void item6QtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item6QtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item6QtyActionPerformed

    private void item1AddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item1AddToCartActionPerformed
        String itemID = item1ID.getText();
        String itemName = item1desc.getText();
//        int avaQty = Integer.parseInt(item1AvailableQty.getText());
        int qty = Integer.parseInt(item1Qty.getText());
//        int finalQty = avaQty - qty;
        String unitPrice = item1Price.getText();
        float uniPrice = Float.parseFloat(unitPrice);
        float price = uniPrice * qty;
//        

        float amout = Float.parseFloat(jLabel10.getText());
        float finalAmount = amout + price;
        jLabel10.setText(Float.toString(finalAmount));

        Object[] rowData = {itemName, itemID, qty, price};
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        defaultTableModel.addRow(rowData);
    }//GEN-LAST:event_item1AddToCartActionPerformed

    private void item2AddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item2AddToCartActionPerformed
        String itemID = item2ID.getText();
        String itemName = item2desc.getText();
//        int avaQty = Integer.parseInt(item1AvailableQty.getText());
        int qty = Integer.parseInt(item2Qty.getText());
//        int finalQty = avaQty - qty;
        String unitPrice = item2Price.getText();
        float uniPrice = Float.parseFloat(unitPrice);
        float price = uniPrice * qty;

        float amout = Float.parseFloat(jLabel10.getText());
        float finalAmount = amout + price;
        jLabel10.setText(Float.toString(finalAmount));

        Object[] rowData = {itemName, itemID, qty, price};
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        defaultTableModel.addRow(rowData);
    }//GEN-LAST:event_item2AddToCartActionPerformed

    private void item3AddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item3AddToCartActionPerformed
        String itemID = item3ID.getText();
        String itemName = item3desc.getText();
//        int avaQty = Integer.parseInt(item1AvailableQty.getText());
        int qty = Integer.parseInt(item3Qty.getText());
//        int finalQty = avaQty - qty;
        String unitPrice = item3Price.getText();
        float uniPrice = Float.parseFloat(unitPrice);
        float price = uniPrice * qty;

        float amout = Float.parseFloat(jLabel10.getText());
        float finalAmount = amout + price;
        jLabel10.setText(Float.toString(finalAmount));

        Object[] rowData = {itemName, itemID, qty, price};
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        defaultTableModel.addRow(rowData);
    }//GEN-LAST:event_item3AddToCartActionPerformed

    private void item4AddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item4AddToCartActionPerformed
        String itemID = item4ID.getText();
        String itemName = item4desc.getText();
//        int avaQty = Integer.parseInt(item1AvailableQty.getText());
        int qty = Integer.parseInt(item4Qty.getText());
//        int finalQty = avaQty - qty;
        String unitPrice = item4Price.getText();
        float uniPrice = Float.parseFloat(unitPrice);
        float price = uniPrice * qty;

        float amout = Float.parseFloat(jLabel10.getText());
        float finalAmount = amout + price;
        jLabel10.setText(Float.toString(finalAmount));

        Object[] rowData = {itemName, itemID, qty, price};
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        defaultTableModel.addRow(rowData);
    }//GEN-LAST:event_item4AddToCartActionPerformed

    private void item5AddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item5AddToCartActionPerformed
        String itemID = item5ID.getText();
        String itemName = item5desc.getText();
//        int avaQty = Integer.parseInt(item1AvailableQty.getText());
        int qty = Integer.parseInt(item5Qty.getText());
//        int finalQty = avaQty - qty;
        String unitPrice = item5Price.getText();
        float uniPrice = Float.parseFloat(unitPrice);
        float price = uniPrice * qty;

        float amout = Float.parseFloat(jLabel10.getText());
        float finalAmount = amout + price;
        jLabel10.setText(Float.toString(finalAmount));

        Object[] rowData = {itemName, itemID, qty, price};
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        defaultTableModel.addRow(rowData);
    }//GEN-LAST:event_item5AddToCartActionPerformed

    private void item6AddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item6AddToCartActionPerformed
        String itemID = item6ID.getText();
        String itemName = item6desc.getText();
//        int avaQty = Integer.parseInt(item1AvailableQty.getText());
        int qty = Integer.parseInt(item6Qty.getText());
//        int finalQty = avaQty - qty;
        String unitPrice = item6Price.getText();
        float uniPrice = Float.parseFloat(unitPrice);
        float price = uniPrice * qty;

        float amout = Float.parseFloat(jLabel10.getText());
        float finalAmount = amout + price;
        jLabel10.setText(Float.toString(finalAmount));

        Object[] rowData = {itemName, itemID, qty, price};
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        defaultTableModel.addRow(rowData);
    }//GEN-LAST:event_item6AddToCartActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        ArrayList<Item> modifyItems = new ArrayList<>();
        for (int i = 0; i < defaultTableModel.getRowCount(); i++) {
            String itemID = (String) defaultTableModel.getValueAt(i, 1);
            int qty = (int) defaultTableModel.getValueAt(i, 2);
            modifyItems.add(new Item(itemID, qty));
        }

        ObjectOutputStream toTheServer = null;
        try {
            toTheServer = new ObjectOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(mainwindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            //            Item item = new Item();
            toTheServer.writeObject(modifyItems);

            ObjectInputStream fromTheServer = new ObjectInputStream(socket.getInputStream());
            ArrayList<Item> allItems = (ArrayList<Item>) fromTheServer.readObject();

//            getAllItems(allItems);
            setAllItems(allItems);

            JOptionPane.showMessageDialog(this, "Database Updated..");
            clearAll();

        } catch (IOException ex) {
            Logger.getLogger(mainwindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(mainwindow.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        double netAmount = Double.parseDouble(jLabel10.getText());
        double payment = Double.parseDouble(jTextField1.getText());
        double balance = payment - netAmount;
        jLabel15.setText(Double.toString(balance));
        if (payment >= netAmount) {
            jButton1.setEnabled(true);
        }

    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainwindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton item1AddToCart;
    private javax.swing.JLabel item1AvailableQty;
    private javax.swing.JLabel item1ID;
    private javax.swing.JLabel item1Price;
    private javax.swing.JTextField item1Qty;
    private javax.swing.JLabel item1Rate;
    private javax.swing.JLabel item1desc;
    private javax.swing.JButton item2AddToCart;
    private javax.swing.JLabel item2AvailableQty;
    private javax.swing.JLabel item2ID;
    private javax.swing.JLabel item2Price;
    private javax.swing.JTextField item2Qty;
    private javax.swing.JLabel item2Rate;
    private javax.swing.JLabel item2desc;
    private javax.swing.JButton item3AddToCart;
    private javax.swing.JLabel item3AvailableQty;
    private javax.swing.JLabel item3ID;
    private javax.swing.JLabel item3Price;
    private javax.swing.JTextField item3Qty;
    private javax.swing.JLabel item3Rate;
    private javax.swing.JLabel item3desc;
    private javax.swing.JButton item4AddToCart;
    private javax.swing.JLabel item4AvailableQty;
    private javax.swing.JLabel item4ID;
    private javax.swing.JLabel item4Price;
    private javax.swing.JTextField item4Qty;
    private javax.swing.JLabel item4Rate;
    private javax.swing.JLabel item4desc;
    private javax.swing.JButton item5AddToCart;
    private javax.swing.JLabel item5AvailableQty;
    private javax.swing.JLabel item5ID;
    private javax.swing.JLabel item5Price;
    private javax.swing.JTextField item5Qty;
    private javax.swing.JLabel item5Rate;
    private javax.swing.JLabel item5desc;
    private javax.swing.JButton item6AddToCart;
    private javax.swing.JLabel item6AvailableQty;
    private javax.swing.JLabel item6ID;
    private javax.swing.JLabel item6Price;
    private javax.swing.JTextField item6Qty;
    private javax.swing.JLabel item6Rate;
    private javax.swing.JLabel item6desc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables

    private void getClock() {
        new Thread() {
            public void run() {
                while (timeRun == 0) {
                    Calendar calender = new GregorianCalendar();
                    int hour = calender.get(Calendar.HOUR);
                    int min = calender.get(Calendar.MINUTE);
                    int sec = calender.get(Calendar.SECOND);
                    int AM_PM = calender.get(Calendar.AM_PM);

                    String day_night = "";
                    if (AM_PM == 1) {
                        day_night = "PM";
                    } else {
                        day_night = "AM";
                    }
                    String time = hour + ":" + min + ":" + sec + " " + day_night;

                    timeLabel.setText(time);
                }
            }
        }.start();
    }

    /*private void getAllItems(ArrayList<Item> allItems) {
        int y = 10;
        int x = -70;
//        ScrollPane scrollPane=new ScrollPane();
//        scrollPane.setSize(jPanel3.getSize());
////        scrollPane.setViewportView(jPanel4);
//        JPanel jPanel4=new JPanel();
//        jPanel4.setSize(scrollPane.getSize());
//        scrollPane.add(jPanel4);
//        jPanel3.add(scrollPane);

        for (Item allItem : allItems) {
            JLabel label3 = new JLabel();
            label3.setVisible(true);
            label3.setOpaque(false);
            label3.setFont(new java.awt.Font("Tahoma", 0, 14));
//            label3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            label3.setText(allItem.getName());
            jPanel5.setLayout(null);
            label3.setBounds(x + 80, y + 10, 200, 25);
            jPanel5.add(label3);
            
            JLabel idlabel = new JLabel();
            idlabel.setVisible(true);
            idlabel.setOpaque(false);
            idlabel.setFont(new java.awt.Font("Tahoma", 0, 14));
//            idlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            idlabel.setText(" Rate : " + Integer.toString(allItem.getRate())+"%");
            jPanel5.setLayout(null);
            idlabel.setBounds(x + 80, y + 40, 200, 25);
            jPanel5.add(idlabel);

            JLabel label4 = new JLabel();
            label4.setVisible(true);
            label4.setOpaque(false);
            label4.setFont(new java.awt.Font("Tahoma", 0, 14));
//            label4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            label4.setText(" Rs. "+ Float.toString((float) allItem.getPrice()));
            jPanel5.setLayout(null);
            label4.setBounds(x + 310, y + 20, 90, 25);
            jPanel5.add(label4);

            JLabel label5 = new JLabel();
            label5.setVisible(true);
            label5.setOpaque(false);
            label5.setFont(new java.awt.Font("Tahoma", 0, 14));
//            label5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            label5.setText("    "+Integer.toString(allItem.getAvailableQty()));
            jPanel5.setLayout(null);
            label5.setBounds(x + 430, y + 20, 90, 25);
            jPanel5.add(label5);

            JTextField textField = new JTextField();
            textField.setVisible(true);
            textField.setOpaque(false);
            textField.setFont(new java.awt.Font("Tahoma", 0, 14));
            textField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            textField.setText("0");
            jPanel5.setLayout(null);
            textField.setBounds(x + 550, y + 20, 90, 25);
            jPanel5.add(textField);

            JButton btn = new JButton();
            btn.setVisible(true);
            btn.setOpaque(false);
            btn.setFont(new java.awt.Font("Tahoma", 0, 14));
//            btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            btn.setText("Add To Cart");
            jPanel5.setLayout(null);
            btn.setBounds(x + 670, y + 15, 110, 35);
            jPanel5.add(btn);

            jPanel5.repaint();

            y += 80;
        }

        for (int i = 0; i < 5; i++) {
//            JLabel label2 = new JLabel();
//            label2.setVisible(true);
//            label2.setOpaque(false);
//            label2.setFont(new java.awt.Font("Tahoma", 0, 14));
//            label2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//            label2.setText(" asasa");
//            jPanel5.setLayout(null);
//            label2.setBounds(x, y, 70, 70);
//            jPanel5.add(label2);
//            jPanel3.repaint();

            
        }
    }
     */
    private void connectSocket() {
        try {
            socket = new Socket("localhost", 4000);
            System.out.println("connect with server..");

            ObjectInputStream fromTheServer = new ObjectInputStream(socket.getInputStream());
            ArrayList<Item> allItems = (ArrayList<Item>) fromTheServer.readObject();

//            getAllItems(allItems);
            setAllItems(allItems);
//            System.out.println(itemss.getName());
            for (Item allItem : allItems) {
                System.out.println(allItem.getName());
            }

        } catch (IOException ex) {
            Logger.getLogger(mainwindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(mainwindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setAllItems(ArrayList<Item> allItems) {
        Item items = allItems.get(0);
        item1desc.setText(items.getName());
        item1Rate.setText(" Rate :" + Integer.toString(items.getRate()) + "%");
        item1ID.setText(items.getId());
        item1Price.setText(Float.toString((float) items.getPrice()));
        item1AvailableQty.setText(Integer.toString(items.getAvailableQty()));

        items = allItems.get(1);
        item2desc.setText(items.getName());
        item2Rate.setText(" Rate :" + Integer.toString(items.getRate()) + "%");
        item2ID.setText(items.getId());
        item2Price.setText(Float.toString((float) items.getPrice()));
        item2AvailableQty.setText(Integer.toString(items.getAvailableQty()));

        items = allItems.get(2);
        item3desc.setText(items.getName());
        item3Rate.setText(" Rate :" + Integer.toString(items.getRate()) + "%");
        item3ID.setText(items.getId());
        item3Price.setText(Float.toString((float) items.getPrice()));
        item3AvailableQty.setText(Integer.toString(items.getAvailableQty()));

        items = allItems.get(3);
        item4desc.setText(items.getName());
        item4Rate.setText(" Rate :" + Integer.toString(items.getRate()) + "%");
        item4ID.setText(items.getId());
        item4Price.setText(Float.toString((float) items.getPrice()));
        item4AvailableQty.setText(Integer.toString(items.getAvailableQty()));

        items = allItems.get(4);
        item5desc.setText(items.getName());
        item5Rate.setText(" Rate :" + Integer.toString(items.getRate()) + "%");
        item5ID.setText(items.getId());
        item5Price.setText(Float.toString((float) items.getPrice()));
        item5AvailableQty.setText(Integer.toString(items.getAvailableQty()));

        items = allItems.get(5);
        item6desc.setText(items.getName());
        item6Rate.setText(" Rate :" + Integer.toString(items.getRate()) + "%");
        item6ID.setText(items.getId());
        item6Price.setText(Float.toString((float) items.getPrice()));
        item6AvailableQty.setText(Integer.toString(items.getAvailableQty()));
    }

    private void clearAll() {
        item1Qty.setText("");
        item2Qty.setText("");
        item3Qty.setText("");
        item4Qty.setText("");
        item5Qty.setText("");
        item6Qty.setText("");
        jLabel10.setText("0.00");
        jTextField1.setText("");
        jLabel15.setText("0.00");
        
        DefaultTableModel defaultTableModel=(DefaultTableModel) jTable1.getModel();
        defaultTableModel.setRowCount(0);
    }

}
